name = "cloudflare-docker-proxy"
compatibility_date = "2023-12-01"

[dev]
ip = "0.0.0.0"
port = 8787
local_protocol = "http"

[env.vars]
CUSTOM_DOMAIN = "ruili.site"

[env.dev.vars]
MODE = "debug"
TARGET_UPSTREAM = "https://registry-1.docker.io"
CUSTOM_DOMAIN = "ruili.site"

[env.production]
name = "cloudflare-docker-proxy"
 routes = [
   { pattern = "docker.ruili.site", custom_domain = true },
   { pattern = "quay.ruili.site", custom_domain = true },
   { pattern = "gcr.ruili.site", custom_domain = true },
   { pattern = "k8s-gcr.ruili.site", custom_domain = true },
   { pattern = "k8s.ruili.site", custom_domain = true },
   { pattern = "ghcr.ruili.site", custom_domain = true },
   { pattern = "cloudsmith.ruili.site", custom_domain = true },
]

[env.production.vars]
MODE = "production"
TARGET_UPSTREAM = ""

[env.staging]
name = "cloudflare-docker-proxy-staging"
route = { pattern = "docker-staging.ruili.site", custom_domain = true }

[env.staging.vars]
MODE = "staging"
TARGET_UPSTREAM = ""
